// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "maebot_motor_feedback_t.h"

static int __maebot_motor_feedback_t_hash_computed;
static int64_t __maebot_motor_feedback_t_hash;

int64_t __maebot_motor_feedback_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __maebot_motor_feedback_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__maebot_motor_feedback_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0xc6e2d0147e5217fcLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __maebot_motor_feedback_t_get_hash(void)
{
    if (!__maebot_motor_feedback_t_hash_computed) {
        __maebot_motor_feedback_t_hash = __maebot_motor_feedback_t_hash_recursive(NULL);
        __maebot_motor_feedback_t_hash_computed = 1;
    }

    return __maebot_motor_feedback_t_hash;
}

int __maebot_motor_feedback_t_encode_array(void *buf, int offset, int maxlen, const maebot_motor_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].encoder_left_ticks), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].encoder_right_ticks), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_current_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_current_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_left_commanded_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_right_commanded_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_left_actual_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_right_actual_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int maebot_motor_feedback_t_encode(void *buf, int offset, int maxlen, const maebot_motor_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __maebot_motor_feedback_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __maebot_motor_feedback_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __maebot_motor_feedback_t_encoded_array_size(const maebot_motor_feedback_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int32_t_encoded_array_size(&(p[element].encoder_left_ticks), 1);

        size += __int32_t_encoded_array_size(&(p[element].encoder_right_ticks), 1);

        size += __int32_t_encoded_array_size(&(p[element].motor_current_left), 1);

        size += __int32_t_encoded_array_size(&(p[element].motor_current_right), 1);

        size += __float_encoded_array_size(&(p[element].motor_left_commanded_speed), 1);

        size += __float_encoded_array_size(&(p[element].motor_right_commanded_speed), 1);

        size += __float_encoded_array_size(&(p[element].motor_left_actual_speed), 1);

        size += __float_encoded_array_size(&(p[element].motor_right_actual_speed), 1);

    }
    return size;
}

int maebot_motor_feedback_t_encoded_size(const maebot_motor_feedback_t *p)
{
    return 8 + __maebot_motor_feedback_t_encoded_array_size(p, 1);
}

size_t maebot_motor_feedback_t_struct_size(void)
{
    return sizeof(maebot_motor_feedback_t);
}

int maebot_motor_feedback_t_num_fields(void)
{
    return 9;
}

int maebot_motor_feedback_t_get_field(const maebot_motor_feedback_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= maebot_motor_feedback_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 1: {
            f->name = "encoder_left_ticks";
            f->type = LCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void *) &p->encoder_left_ticks;
            return 0;
        }
        
        case 2: {
            f->name = "encoder_right_ticks";
            f->type = LCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void *) &p->encoder_right_ticks;
            return 0;
        }
        
        case 3: {
            f->name = "motor_current_left";
            f->type = LCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void *) &p->motor_current_left;
            return 0;
        }
        
        case 4: {
            f->name = "motor_current_right";
            f->type = LCM_FIELD_INT32_T;
            f->typestr = "int32_t";
            f->num_dim = 0;
            f->data = (void *) &p->motor_current_right;
            return 0;
        }
        
        case 5: {
            f->name = "motor_left_commanded_speed";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->motor_left_commanded_speed;
            return 0;
        }
        
        case 6: {
            f->name = "motor_right_commanded_speed";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->motor_right_commanded_speed;
            return 0;
        }
        
        case 7: {
            f->name = "motor_left_actual_speed";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->motor_left_actual_speed;
            return 0;
        }
        
        case 8: {
            f->name = "motor_right_actual_speed";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->motor_right_actual_speed;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *maebot_motor_feedback_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) maebot_motor_feedback_t_encode;
        typeinfo.decode         = (lcm_decode_t) maebot_motor_feedback_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) maebot_motor_feedback_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) maebot_motor_feedback_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  maebot_motor_feedback_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) maebot_motor_feedback_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) maebot_motor_feedback_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __maebot_motor_feedback_t_get_hash;
    }
    
    return &typeinfo;
}
int __maebot_motor_feedback_t_decode_array(const void *buf, int offset, int maxlen, maebot_motor_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].encoder_left_ticks), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].encoder_right_ticks), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_current_left), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_current_right), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_left_commanded_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_right_commanded_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_left_actual_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].motor_right_actual_speed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __maebot_motor_feedback_t_decode_array_cleanup(maebot_motor_feedback_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int32_t_decode_array_cleanup(&(p[element].encoder_left_ticks), 1);

        __int32_t_decode_array_cleanup(&(p[element].encoder_right_ticks), 1);

        __int32_t_decode_array_cleanup(&(p[element].motor_current_left), 1);

        __int32_t_decode_array_cleanup(&(p[element].motor_current_right), 1);

        __float_decode_array_cleanup(&(p[element].motor_left_commanded_speed), 1);

        __float_decode_array_cleanup(&(p[element].motor_right_commanded_speed), 1);

        __float_decode_array_cleanup(&(p[element].motor_left_actual_speed), 1);

        __float_decode_array_cleanup(&(p[element].motor_right_actual_speed), 1);

    }
    return 0;
}

int maebot_motor_feedback_t_decode(const void *buf, int offset, int maxlen, maebot_motor_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __maebot_motor_feedback_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __maebot_motor_feedback_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int maebot_motor_feedback_t_decode_cleanup(maebot_motor_feedback_t *p)
{
    return __maebot_motor_feedback_t_decode_array_cleanup(p, 1);
}

int __maebot_motor_feedback_t_clone_array(const maebot_motor_feedback_t *p, maebot_motor_feedback_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int32_t_clone_array(&(p[element].encoder_left_ticks), &(q[element].encoder_left_ticks), 1);

        __int32_t_clone_array(&(p[element].encoder_right_ticks), &(q[element].encoder_right_ticks), 1);

        __int32_t_clone_array(&(p[element].motor_current_left), &(q[element].motor_current_left), 1);

        __int32_t_clone_array(&(p[element].motor_current_right), &(q[element].motor_current_right), 1);

        __float_clone_array(&(p[element].motor_left_commanded_speed), &(q[element].motor_left_commanded_speed), 1);

        __float_clone_array(&(p[element].motor_right_commanded_speed), &(q[element].motor_right_commanded_speed), 1);

        __float_clone_array(&(p[element].motor_left_actual_speed), &(q[element].motor_left_actual_speed), 1);

        __float_clone_array(&(p[element].motor_right_actual_speed), &(q[element].motor_right_actual_speed), 1);

    }
    return 0;
}

maebot_motor_feedback_t *maebot_motor_feedback_t_copy(const maebot_motor_feedback_t *p)
{
    maebot_motor_feedback_t *q = (maebot_motor_feedback_t*) malloc(sizeof(maebot_motor_feedback_t));
    __maebot_motor_feedback_t_clone_array(p, q, 1);
    return q;
}

void maebot_motor_feedback_t_destroy(maebot_motor_feedback_t *p)
{
    __maebot_motor_feedback_t_decode_array_cleanup(p, 1);
    free(p);
}

int maebot_motor_feedback_t_publish(lcm_t *lc, const char *channel, const maebot_motor_feedback_t *p)
{
      int max_data_size = maebot_motor_feedback_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = maebot_motor_feedback_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _maebot_motor_feedback_t_subscription_t {
    maebot_motor_feedback_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void maebot_motor_feedback_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    maebot_motor_feedback_t p;
    memset(&p, 0, sizeof(maebot_motor_feedback_t));
    status = maebot_motor_feedback_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding maebot_motor_feedback_t!!!\n", status);
        return;
    }

    maebot_motor_feedback_t_subscription_t *h = (maebot_motor_feedback_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    maebot_motor_feedback_t_decode_cleanup (&p);
}

maebot_motor_feedback_t_subscription_t* maebot_motor_feedback_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    maebot_motor_feedback_t_handler_t f, void *userdata)
{
    maebot_motor_feedback_t_subscription_t *n = (maebot_motor_feedback_t_subscription_t*)
                       malloc(sizeof(maebot_motor_feedback_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 maebot_motor_feedback_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg maebot_motor_feedback_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int maebot_motor_feedback_t_subscription_set_queue_capacity (maebot_motor_feedback_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int maebot_motor_feedback_t_unsubscribe(lcm_t *lcm, maebot_motor_feedback_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe maebot_motor_feedback_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

