/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package eecs467.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class dynamixel_command_list_t implements lcm.lcm.LCMEncodable
{
    public int len;
    public eecs467.lcmtypes.dynamixel_command_t commands[];
 
    public dynamixel_command_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x131b5b70389b084fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(eecs467.lcmtypes.dynamixel_command_list_t.class))
            return 0L;
 
        classes.add(eecs467.lcmtypes.dynamixel_command_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + eecs467.lcmtypes.dynamixel_command_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.len); 
 
        for (int a = 0; a < this.len; a++) {
            this.commands[a]._encodeRecursive(outs); 
        }
 
    }
 
    public dynamixel_command_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public dynamixel_command_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static eecs467.lcmtypes.dynamixel_command_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        eecs467.lcmtypes.dynamixel_command_list_t o = new eecs467.lcmtypes.dynamixel_command_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.len = ins.readInt();
 
        this.commands = new eecs467.lcmtypes.dynamixel_command_t[(int) len];
        for (int a = 0; a < this.len; a++) {
            this.commands[a] = eecs467.lcmtypes.dynamixel_command_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public eecs467.lcmtypes.dynamixel_command_list_t copy()
    {
        eecs467.lcmtypes.dynamixel_command_list_t outobj = new eecs467.lcmtypes.dynamixel_command_list_t();
        outobj.len = this.len;
 
        outobj.commands = new eecs467.lcmtypes.dynamixel_command_t[(int) len];
        for (int a = 0; a < this.len; a++) {
            outobj.commands[a] = this.commands[a].copy();
        }
 
        return outobj;
    }
 
}

