/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package eecs467.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class maebot_laser_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public boolean laser_power;
 
    public maebot_laser_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3b34ecb0d057173eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(eecs467.lcmtypes.maebot_laser_t.class))
            return 0L;
 
        classes.add(eecs467.lcmtypes.maebot_laser_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte( this.laser_power ? 1 : 0); 
 
    }
 
    public maebot_laser_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public maebot_laser_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static eecs467.lcmtypes.maebot_laser_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        eecs467.lcmtypes.maebot_laser_t o = new eecs467.lcmtypes.maebot_laser_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.laser_power = ins.readByte()!=0;
 
    }
 
    public eecs467.lcmtypes.maebot_laser_t copy()
    {
        eecs467.lcmtypes.maebot_laser_t outobj = new eecs467.lcmtypes.maebot_laser_t();
        outobj.utime = this.utime;
 
        outobj.laser_power = this.laser_power;
 
        return outobj;
    }
 
}

