/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package eecs467.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class maebot_sensor_data_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public short accel[];
    public short gyro[];
    public long gyro_int[];
    public int line_sensors[];
    public int range;
    public boolean user_button_pressed;
    public boolean power_button_pressed;
 
    public maebot_sensor_data_t()
    {
        accel = new short[3];
        gyro = new short[3];
        gyro_int = new long[3];
        line_sensors = new int[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x61904126132f424dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(eecs467.lcmtypes.maebot_sensor_data_t.class))
            return 0L;
 
        classes.add(eecs467.lcmtypes.maebot_sensor_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeShort(this.accel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeShort(this.gyro[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeLong(this.gyro_int[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeInt(this.line_sensors[a]); 
        }
 
        outs.writeInt(this.range); 
 
        outs.writeByte( this.user_button_pressed ? 1 : 0); 
 
        outs.writeByte( this.power_button_pressed ? 1 : 0); 
 
    }
 
    public maebot_sensor_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public maebot_sensor_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static eecs467.lcmtypes.maebot_sensor_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        eecs467.lcmtypes.maebot_sensor_data_t o = new eecs467.lcmtypes.maebot_sensor_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.accel = new short[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accel[a] = ins.readShort();
        }
 
        this.gyro = new short[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyro[a] = ins.readShort();
        }
 
        this.gyro_int = new long[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyro_int[a] = ins.readLong();
        }
 
        this.line_sensors = new int[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.line_sensors[a] = ins.readInt();
        }
 
        this.range = ins.readInt();
 
        this.user_button_pressed = ins.readByte()!=0;
 
        this.power_button_pressed = ins.readByte()!=0;
 
    }
 
    public eecs467.lcmtypes.maebot_sensor_data_t copy()
    {
        eecs467.lcmtypes.maebot_sensor_data_t outobj = new eecs467.lcmtypes.maebot_sensor_data_t();
        outobj.utime = this.utime;
 
        outobj.accel = new short[(int) 3];
        System.arraycopy(this.accel, 0, outobj.accel, 0, 3); 
        outobj.gyro = new short[(int) 3];
        System.arraycopy(this.gyro, 0, outobj.gyro, 0, 3); 
        outobj.gyro_int = new long[(int) 3];
        System.arraycopy(this.gyro_int, 0, outobj.gyro_int, 0, 3); 
        outobj.line_sensors = new int[(int) 3];
        System.arraycopy(this.line_sensors, 0, outobj.line_sensors, 0, 3); 
        outobj.range = this.range;
 
        outobj.user_button_pressed = this.user_button_pressed;
 
        outobj.power_button_pressed = this.power_button_pressed;
 
        return outobj;
    }
 
}

