/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package eecs467.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class maebot_command_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public short motor_left_speed;
    public short motor_right_speed;
    public byte laser_power;
 
    public maebot_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x23a496c99b6f626fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(eecs467.lcmtypes.maebot_command_t.class))
            return 0L;
 
        classes.add(eecs467.lcmtypes.maebot_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.motor_left_speed); 
 
        outs.writeShort(this.motor_right_speed); 
 
        outs.writeByte(this.laser_power); 
 
    }
 
    public maebot_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public maebot_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static eecs467.lcmtypes.maebot_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        eecs467.lcmtypes.maebot_command_t o = new eecs467.lcmtypes.maebot_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.motor_left_speed = ins.readShort();
 
        this.motor_right_speed = ins.readShort();
 
        this.laser_power = ins.readByte();
 
    }
 
    public eecs467.lcmtypes.maebot_command_t copy()
    {
        eecs467.lcmtypes.maebot_command_t outobj = new eecs467.lcmtypes.maebot_command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.motor_left_speed = this.motor_left_speed;
 
        outobj.motor_right_speed = this.motor_right_speed;
 
        outobj.laser_power = this.laser_power;
 
        return outobj;
    }
 
}

